### ISSUE TITLE
API calls on exception

### ISSUE THREAD

**Issue by harrier-lcc** [FaroukY/ustfreshers#4]
If API call fails, the SunsetSunrise may produced an Connection Exception and error.

For example this:
```String result = restTemplate.getForObject("https://api.sunrise-sunset.org/json?lat=22.3364&lng=114.2655", String.class);```

If it fail to connect the website, what will it output or will it crash?

**Comment by FaroukY** [comment]
@harrier-lcc Good catch, can you add some exception handling for it, request another PR after and we'll handle it. Thanks!

**Comment by donfour** [comment]
@harrier-lcc Good catch, lucky that you found the issue!
